function [w,ft] = ft_carga(registro, filtro)
%FT_CARGA Carga un archivo de roca y suelo y calcula la funcion de
%transferencia

[w, ft] = ft_gen(strcat(registro, strcat('/', strcat(registro, '-sup-z.txt'))), ...
    strcat(registro, strcat('/', strcat(registro, '-sup-ns.txt'))), ...
    strcat(registro, strcat('/', strcat(registro, '-sup-ew.txt'))), ...
    strcat(registro, strcat('/', strcat(registro, '-roca-z.txt'))), ...
    strcat(registro, strcat('/', strcat(registro, '-roca-ns.txt'))), ...
    strcat(registro, strcat('/', strcat(registro, '-roca-ew.txt'))), ...
    filtro);

end